urls.py
from django.urls import path

from mybooks import views
from mybooks.views import (AuthorList, AuthorListRecent, BookView, BooksAlpha,
                           BooksOrderRead,
                           BooksToRead, SeriesList)

app_name = 'mybooks'
urlpatterns = [
    # Index Views

    # / Latest 10 books read
    path('', BookView.as_view(), name='books'),
    # Book /books  # order alphabetical
    path('books/', BooksAlpha.as_view(), name='allbooks_alphabetical'),
    # Book /books_orderread  # order read
    path('books_orderread/', BooksOrderRead.as_view(),
         name='allbooks_orderread'),
    # Book /read  - books to read next
    path('read/', BooksToRead.as_view(), name='read'),
    path('read/soon/', BooksToRead.as_view(), name='now'),
    path('read/now/', BooksToRead.as_view(), name='soon'),

    # Author /author
    path('authors/', AuthorList.as_view(), name='authors'),
    path('authors_recent/', AuthorListRecent.as_view(), name='authors_recent'),

    # Series /series
    path('series/', SeriesList.as_view(), name='series'),

    # Detail Views all /model/pk e.g. /mybooks/book/5
    path('book/<int:pk>/', views.BookDetail.as_view(),
         name='book_detail'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(),
         name='author_detail'),
    path('series/<int:pk>/', views.SeriesDetail.as_view(),
         name='series_detail'),

    # Series given book id /mybooks/5/series not sure why take this route
    path('<int:pk>/series/', views.BookSeries.as_view()),
    path('book/<int:pk>/series/', views.BookSeries.as_view(),
         name='book_series'),

    # Author given book id /mybooks/5/author not sure why take this route
    path('book/<int:pk>/author/', views.BookAuthor.as_view(),
         name='book_author'),
    path('<int:pk>/author/', views.BookAuthor.as_view()),

    # Views for editing
    # model/id/update/
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(),
         name='author_update'),
]

templates/mybooks/author_detail.html
{% extends "mybooks/base.html" %}

<br \><a href="{% url 'mybooks:authors' %}">Authors</a>

{% block heading %}{{ author }}{% endblock %}
{% block body %}
<table>
  <tr>
    <th>Notes</th><td>{{ author.notes }}</td>
  </tr>
  <tr>
    <th>Rating</th><td>{{ author.rating }}</td>
  </tr>
    <th>Added</th><td>{{ author.date_added }}</td>
  </tr>
  </tr>
    <th></th><td><a
           href="{% url 'mybooks:author_update' author.id %}">Update</a></td>
  </tr>
</table>

<h2>Books</h2>
{% if books %}
    <ul>
    {% for book in books %}
        <li>
           <a href="{% url 'mybooks:book_detail' book.id %}" >{{ book.title }}</a> =>
           {% if book.series %}
             (<a
           href="{% url 'mybooks:series_detail' book.series.id %}" >{{ book.series }}</a>)
           {% endif %}
      </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No books by this author:-(.</p>
{% endif %}
{% endblock %}

templates/mybooks/author_list.html
{% extends "mybooks/base.html" %}
{% block heading %}My Authors{% endblock %}

{% block body %}
    {% if author_list %}
        <ul>
          {% for author in author_list %}
              <li><a href="{% url 'mybooks:author_detail' author.id %}">
                      {{ author.last }}, {{ author.first }}</a>
                {% if author.books_read %}
                    read: {{author.number_books_read}}
                    {% if author.rating %}
                        rated: {{ author.rating }}
                    {% endif %}
                {% endif %}
              </li>
           {% endfor %}
        </ul>
    {% else %}
        <p>No authors :-(.</p>
    {% endif %}
{% endblock %}

templates/mybooks/author_update.html
{% extends "mybooks/base.html" %}

<br \><a href="{% url 'mybooks:authors' %}">Authors</a>

{% block heading %}{{ author }}{% endblock %}

{% block body %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'mybooks:author_update' pk %}" method="post">
{% csrf_token %}

<table>
  <tr>
    <th>First</th>
    <td><input type="text" name="first" id="first" value="{{ author.first }}"</td>
  </tr>
  <tr>
    <th>Last</th>
    <td><input type="text" name="last" id="last" value="{{ author.last }}"</td>
  </tr>
  <tr>
    <th>Notes</th>
    <td><textarea name="notes" id="notes" rows=5 cols=50>
{% if author.notes %}{{ author.notes }}{% endif %}</textarea></td>
  </tr>
  <tr>
    <th>Rating</th>
    <td><input type="text" name="rating" id="rating"
         value="{% if author.rating %}{{ author.rating }}{% endif %}"/td>
  </tr>
  <tr>
    <th>Added</th> <td>{{ author.date_added }}</td>
  </tr>
</table>
<input type="submit" id="submit" name="submit" value="Update" />
</form>
{% endblock %}

templates/mybooks/base.html
<a href="{% url 'mybooks:allbooks_alphabetical' %}">Books Alphabetical</a> |
<a href="{% url 'mybooks:allbooks_orderread' %}">Books order read</a> |
Books to Read <a href="{% url 'mybooks:now' %}">Now</a>
  <a href="{% url 'mybooks:read' %}">Soon</a> ||
<a href="{% url 'mybooks:series' %}">Series</a> |
<a href="{% url 'mybooks:authors' %}">Authors</a>

<h1>{% block heading %}{% endblock %}</h1>
{% block body %}{% endblock %}

templates/mybooks/book_detail.html
{% extends "mybooks/base.html" %}
{% block heading %}{{book.title}}{% endblock %}

{% block body %}
<table>
  <tr>
    <th><a href="{% url 'mybooks:books' %}">Books</a></th>
    <td><a target="_" href="/admin/mybooks/book/{{ book.id }}/">Edit</a></td></tr>
  <tr>
    <th>Author</th><td><a href="{% url 'mybooks:author_detail' book.author.id %}">
      {{ book.author }}</a></td>
  </tr>
  <tr>
    <th>Series</th><td>
      {% if book.series %}
          <a href="{% url 'mybooks:series_detail' book.series.id %}">
          {{ book.series }}</a>
          {% if book.series_book_number %}
             ({{ book.series_book_number }})
          {% endif %}
      {% else %}
          -
      {% endif %}
      </td>
  </tr>
  <tr>
    <th>Next</th><td>{{ book.series_next }}</td>
  </tr>
  <tr>
    <th>Status</th><td>{{ book.status }}</td>
  </tr>
  <tr>
    <th>Description</th><td>{{ book.description }}</td>
  </tr>
  <tr>
    <th>Notes</th><td>{{ book.notes }}</td>
  </tr>
  <tr>
    <th>Rating</th><td>{{ book.rating }}</td>
  </tr>
  <tr>
    <th>Read</th><td>{{ book.date_read }}</td>
  </tr>
  <tr>
    <th>Added</th><td>{{ book.date_added }}</td>
  </tr>
</table>
{% endblock %}

templates/mybooks/book_list.html
{% extends "mybooks/base.html" %}
{% block heading %}
{% if list_title %}
  {{ list_title }}
{% else %}
  My Books
{% endif %}
{% endblock %}

{% block body %}
{% if latest_book_list %}
    <ul>
    {% for book in latest_book_list %}
        <li>
           <a href="{% url 'mybooks:book_detail' book.id %}" >{{ book.title }}</a>
           {% if book.series %}
             (<a href="{% url 'mybooks:series_detail' book.series.pk %}">{{ book.series }}
                      {{ book.series_book_number }}</a>)
           {% endif %}
           => <a
           href="{% url 'mybooks:author_detail' book.author.pk %}" >{{ book.author }}</a>
           {% if book.date_read %}
              <em>{{ book.read_recently }}</em>
           {% endif %}
           {% if not book.status == 'R' %}
              ({{ book.print_status }})
           {% endif %}
      </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No books :-(.</p>
{% endif %}
{% endblock %}

templates/mybooks/book_list_to_read.html
{% extends "mybooks/base.html" %}
{% block heading %}
{% if list_title %}
  {{ list_title }}
{% else %}
  My Books
{% endif %}
{% endblock %}

{% block body %}

<h3>Series to READ</h3>

<h4>Started</h4>
<p> <em>X</em> book not in local library
{% if latest_book_list_series_started %}
    <ul>
    {% for book in latest_book_list_series_started %}
        <li>
           {% if book.local_library == False %}
              <em>X </em>
           {% endif %}
           <a href="{% url 'mybooks:author_detail' book.author.pk %}" >{{ book.author }}</a>
           =>
           <a href="{% url 'mybooks:book_detail' book.id %}" >{{ book.title }}</a>
           =>
           <a href="{% url 'mybooks:series_detail' book.series.pk %}" >
                   {{ book.series }} ({{ book.series_book_number }})</a>
           {% if book.local_library != None %}
               {{ book.last_changed }}
           {% endif %}
           {{book.short_description}}
      </li>
    {% endfor %}
    </ul>
{% endif %}


<h4>Not Started</h4>
{% if latest_book_list_series %}
    <ul>
    {% for book in latest_book_list_series %}
        <li>
           {% if book.local_library == False %}
               <em>X </em>
           {% endif %}
           <a href="{% url 'mybooks:author_detail' book.author.pk %}" >{{ book.author }}</a>
           => <a href="{% url 'mybooks:book_detail' book.id %}" >{{ book.title }}
           ({{ book.series_book_number }})</a>
           =>
           <a href="{% url 'mybooks:series_detail' book.series.pk %}" >{{ book.series }}</a>
           {% if book.local_library != None %}
               {{ book.last_changed }}
           {% endif %}
      </li>
    {% endfor %}
    </ul>
{% endif %}


<h3>Books to Read</h3>
{% if latest_book_list %}
    <ul>
    {% for book in latest_book_list %}
        <li>
           {% if book.local_library == False %}
               <em>X </em>
           {% endif %}
           <a href="{% url 'mybooks:author_detail' book.author.pk %}" >{{ book.author }}</a>
           =>
           <a href="{% url 'mybooks:book_detail' book.id %}" >{{ book.title }}</a>
           {% if book.local_library != None %}
               {{ book.last_changed }}
           {% endif %}
      </li>
    {% endfor %}
    </ul>
{% endif %}
{% endblock %}

templates/mybooks/series_detail.html
{% extends "mybooks/base.html" %}

<br \><a href="{% url 'mybooks:series' %}">Series</a>

{% block heading %}{{ series }}{% endblock %}

{% block body %}
<table>
  {% if series.primary_author %}
    <tr>
      <th>Author</th><td><a href="{% url 'mybooks:author_detail' series.primary_author.pk %}">
      {{ series.primary_author }}</a></td>
    </tr>
  {% endif %}
  <tr>
    <th>Next book</th><td>{{ series.next_book }}</td>
  </tr>
  <tr>
    <th>Next series</th><td>{{ series.next }}</td>
  </tr>
  <tr>
  <tr>
    <th>Number</th><td>{{ series.series_number }}</td>
  </tr>
  <tr>
    <th>Description</th><td>{{ series.description }}</td>
  </tr>
  <tr>
    <th>Notes</th><td>{{ series.notes }}</td>
  </tr>
  <tr>
    <th>Rating</th><td>{{ series.rating }}</td>
  </tr>
  <tr>
    <th>Added</th><td>{{ series.date_added }}</td>
  </tr>
</table>

<h2>Books</h2>
{% if books %}
    <ol>
    {% for book in books %}
        <li>
           <a href="{% url 'mybooks:book_detail' book.id %}" >{{ book.title }}</a>
           {% if series.primary_author != book.author %}
             =>
             <a href="{% url 'mybooks:author_detail' book.author.id %}" >{{ book.author }}</a>
           {% endif %}
           {% if book.date_read %}
              <em>{{ book.read_recently }}</em>
           {% endif %}
       </li>
    {% endfor %}
    </ol>
{% else %}
    <p>No books in this series:-(.</p>
{% endif %}
{% endblock %}

templates/mybooks/series_list.html
{% extends "mybooks/base.html" %}
{% block heading %}My Series{% endblock %}
{% block body %}
{% if series_list %}
    <ul>
    {% for s in series_list %}
        <li>
           <a href="{% url 'mybooks:series_detail'  s.id %}" >{{ s.name }}</a>
           {% if s.started %}
               {{ s.display_status }}
               {% if s.rating %}
                    {{ s.rating }}
               {% endif %}
           {% endif %}
      </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No series :-(.</p>
{% endif %}
{% endblock %}